server:
  port: 8081
spring:
  application:
    name: "arus-pensiones-backend"
  devtools:
    add-properties: false
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: "/"
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/arus"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format-sql: true
      show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
